config/routes.rb
Knowledge::Application.routes.draw do
  resources :users do
    collection do
      get :search, to: :search, as: :search
    end
  end

  resources :groups do
    member do
      post :add_user, to: :add_user, as: :add_user
      delete :del_user, to: :del_user, as: :del_user
    end
  end

  resources :file_categories, except: [:show], shallow: true do
    resources :files, except: [:new, :edit, :update]
  end

  resources :board_categories, except: [:show], shallow: true do
    resources :boards do
      member do
        post :comments, to: :comment, as: :comment
        delete "comments/:comment_id", to: :uncomment, as: :uncomment
      end
    end
  end

  resources :qa_categories, shallow: true do
    member do
      post :add_user, to: :add_user, as: :add_user
      delete :del_user, to: :del_user, as: :del_user
    end

    resources :questions do
      member do
        post :answers, to: :answer, as: :answer
        delete "answers/:answer_id", to: :unanswered, as: :unanswered
      end
    end
  end
  
  controller :users do
    get :home, to: :home, as: :home
    get :profile, to: :profile, as: :profile
    patch :profile, to: :update_profile, as: :update_profile
    patch :password, to: :update_password, as: :update_password
  end

  controller :sessions do
    get :signin, to: :new, as: :signin
    post :signin, to: :create, as: :session_create
    get :signout, to: :destroy, as: :signout
  end

  controller :root do
    root to: :index
  end
end

app/models/qa_category.rb
class QaCategory < ActiveRecord::Base
  # Validations
  validates :name, presence: true, length: {maximum: 30}
  validates :description, length: {maximum: 100}

  # Relations
  has_many :answer_users, dependent: :destroy
  has_many :users, through: :answer_users
  has_many :questions, dependent: :destroy

  def category_manager?(user)
    AnswerUser.exists?(qa_category_id: self.id, user_id: user.id)
  end
end

app/controllers/qa_categories_controller.rb
class QaCategoriesController < ApplicationController
  before_action :require_super_user, only: [:show, :new, :edit, :create, :update, :destroy, :add_user, :del_user]
  before_action :set_qa_category, only: [:show, :edit, :update, :destroy, :add_user, :del_user]

  # GET /qa_categories
  def index
    @qa_categories = QaCategory.all
  end

  # GET /qa_categories/new
  def new
    @qa_category = QaCategory.new
  end

  # POST /qa_categories
  def create
    @qa_category = QaCategory.new(qa_category_params)

    if @qa_category.save
      redirect_to qa_categories_path, notice: "カテゴリを追加しました"
    else
      render action: :new
    end
  end

  # PATCH/PUT /qa_categories/1
  def update
    if @qa_category.update(qa_category_params)
      redirect_to qa_categories_path, notice: "カテゴリを変更しました"
    else
      render action: :edit
    end
  end

  # DELETE /qa_categories/1
  def destroy
    @qa_category.destroy
    redirect_to qa_categories_path, notice: "カテゴリを削除しました"
  end

  # POST /qa_categories/1/add_user
  def add_user
    begin
      @user = User.find_by!(email: params[:email])
      AnswerUser.create!(qa_category_id: @qa_category.id, user_id: @user.id)
      redirect_to qa_category_path(@qa_category), notice: "カテゴリに管理者を追加しました" and return
    rescue ActiveRecord::RecordNotFound
      flash.now[:alert] = "指定されたメールアドレスは登録されていません"
    rescue ActiveRecord::RecordInvalid
      flash.now[:alert] = "指定されたユーザは既にカテゴリ管理者です"
    end

    render action: :show
  end

  # DELETE /qa_categories/1/del_user
  def del_user
    @answer_user = AnswerUser.find_by!(qa_category_id: @qa_category.id, user_id: params[:user_id])
    @answer_user.destroy
    redirect_to qa_category_path(@qa_category), notice: "カテゴリから管理者を削除しました"
  end

  private
  def set_qa_category
    @qa_category = QaCategory.find(params[:id])
  end

  def qa_category_params
    params.require(:qa_category).permit(:name, :description)
  end
end

app/views/qa_categories/_form.html.erb
<%= form_for(@qa_category) do |f| %>
  <%= render partial: "shared/errors", object: @qa_category.errors %>

  <div class="form-group">
    <%= f.label :name, "", class: "control-label sr-only" %>
    <%= f.text_field :name, class: "form-control", placeholder: "カテゴリ名", maxlength: 30, required: true %>
  </div>

  <div class="form-group">
    <%= f.label :description, "", class: "control-label sr-only" %>
    <%= f.text_field :description, class: "form-control", placeholder: "説明", maxlength: 100 %>
  </div>

  <%= f.submit "保存", class: "btn btn-primary" %>
<% end %>

app/views/qa_categories/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <ol class="breadcrumb">
        <li><%= link_to "ホーム", home_path %></li>
        <li><%= link_to "Q&A", qa_categories_path %></li>
        <li class="active">カテゴリ編集</li>
      </ol>
      
      <div class="well">
        <legend>カテゴリ編集</legend>

        <%= render "form" %>

        <div class="mt10">
          <%= link_to "削除", qa_category_path(@qa_category), method: :delete, class: "btn btn-danger", data: {confirm: "削除しますか?"} %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/qa_categories/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <ol class="breadcrumb">
        <li><%= link_to "ホーム", home_path %></li>
        <li class="active">Q&A</li>
      </ol>

      <%= render partial: "shared/notice" %>

      <legend>Q&A</legend>

      <% if @qa_categories.count > 0 %>
      <table id="qa_categories" class="table table-striped table-hover table-condensed table-condensed">
        <thead>
          <tr>
            <th>カテゴリ名</th>
            <th>説明</th>
            <% if current_user.super_user? %>
            <th></th>
            <% end %>
          </tr>
        </thead>

        <tbody>
          <% @qa_categories.each do |category| %>
          <tr>
            <td><%= link_to category.name, qa_category_questions_path(category) %></td>
            <td><%= category.description %></td>
            <% if current_user.super_user? %>
            <td align="right">
              <%= link_to qa_category_path(category), class: "btn btn-inverse btn-xs" do %>
              <span class="glyphicon glyphicon-envelope"></span> 設定
              <% end %>
              <%= link_to edit_qa_category_path(category), class: "btn btn-warning btn-xs" do %>
              <span class="glyphicon glyphicon-pencil"></span> 編集
              <% end %>
            </td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
      <% else %>
      <p>カテゴリが登録されていません</p>
      <% end %>

      <% if current_user.super_user? %>
      <div class="mt10">
        <%= link_to "カテゴリ作成", new_qa_category_path, class: "btn btn-inverse" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/qa_categories/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <ol class="breadcrumb">
        <li><%= link_to "ホーム", home_path %></li>
        <li><%= link_to "Q&A", qa_categories_path %></li>
        <li class="active">カテゴリ登録</li>
      </ol>
      
      <div class="well">
        <legend>カテゴリ登録</legend>

        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/qa_categories/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <ol class="breadcrumb">
        <li><%= link_to "ホーム", home_path %></li>
        <li><%= link_to "Q&A", qa_categories_path %></li>
        <li class="active">カテゴリ設定</li>
      </ol>

      <%= render partial: "shared/notice" %>
      <%= render partial: "shared/alert" %>
      
      <div class="well">
        <legend><%= @qa_category.name %>カテゴリの詳細</legend>

        <table class="table table-striped table-bordered table-hover table-condensed table-condensed">
          <tbody>
            <tr>
              <th>カテゴリ名</th>
              <td><%= @qa_category.name %></td>
            </tr>
            <tr>
              <th>説明</th>
              <td><%= @qa_category.description %></td>
            </tr>
          </tbody>
        </table>
      </div>

      <div class="well">
        <legend>カテゴリ管理者</legend>

        <% if @qa_category.users.count > 0 %>
        <table class="table table-striped table-hover table-condensed table-condensed">
          <thead>
            <tr>
              <th>名前</th>
              <th>メールアドレス</th>
              <th></th>
            </tr>
          </thead>

          <tbody>
            <% @qa_category.users.each do |user| %>
            <tr>
              <td><%= link_to "#{user.fullname} (#{user.fullname_kana})", user_path(user) %></td>
              <td><%= user.email %></td>
              <td align="right">
                <%= link_to del_user_qa_category_path(@qa_category, user_id: user.id), class: "btn btn-danger btn-xs", method: :delete, data: {confirm: "削除しますか?"} do %>
                <span class="glyphicon glyphicon-remove-circl"></span> 削除
                <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <% else %>
        <p>カテゴリ管理者は存在しません。</p>
        <% end %>
      </div>

      <div class="well">
        <legend>カテゴリ管理者追加</legend>

        <%= form_tag add_user_qa_category_path(@qa_category) do %>
          <div class="input-group">
            <%= email_field_tag :email, nil, class: "form-control", placeholder: "メールアドレス", maxlength: 100, required: true %>
            <span class="input-group-btn">
              <button class="btn btn-inverse" type="submit">追加</button>
            </span>
          </div>
        <% end %>

        <div class="mt10">
          <a href="#user_search_modal" class="btn btn-inverse btn-sm" data-toggle="modal">ユーザ検索</a>
        </div>
      </div>

      <div id="user_search_modal" class="modal fade">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <a href="javascript:void(0)" class="close" data-dismiss="modal">&times;</a>
              <h4 class="modal-title">ユーザ検索</h4>
            </div>

            <div class="modal-body">
              <div class="input-group">
                <input id="user_keyword" class="form-control" type="text" placeholder="Search">
                <span class="input-group-btn">
                  <button id="execute_user_search" class="btn btn-inverse">検索</button>
                </span>
              </div>

              <div class="mt10">
                <table id="search_user_list" class="table table-striped table-condensed table-hover">
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>