config/routes.rb
Knowledge::Application.routes.draw do
  resources :users do
    collection do
      get :search, to: :search, as: :search
    end
  end

  resources :groups do
    member do
      post :add_user, to: :add_user, as: :add_user
      delete :del_user, to: :del_user, as: :del_user
    end
  end

  resources :file_categories, except: [:show], shallow: true do
    resources :files, except: [:new, :edit, :update]
  end

  resources :board_categories, except: [:show], shallow: true do
    resources :boards do
      member do
        post :comments, to: :comment, as: :comment
        delete "comments/:comment_id", to: :uncomment, as: :uncomment
      end
    end
  end

  resources :qa_categories, shallow: true do
    member do
      post :add_user, to: :add_user, as: :add_user
      delete :del_user, to: :del_user, as: :del_user
    end

    resources :questions do
      member do
        post :answers, to: :answer, as: :answer
        delete "answers/:answer_id", to: :unanswered, as: :unanswered
      end
    end
  end
  
  controller :users do
    get :home, to: :home, as: :home
    get :profile, to: :profile, as: :profile
    patch :profile, to: :update_profile, as: :update_profile
    patch :password, to: :update_password, as: :update_password
  end

  controller :sessions do
    get :signin, to: :new, as: :signin
    post :signin, to: :create, as: :session_create
    get :signout, to: :destroy, as: :signout
  end

  controller :root do
    root to: :index
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  # Validations
  validates :title, presence: true, length: {maximum: 40}
  validates :body, presence: true
  validates :status, presence: true, inclusion: {in: ["新規", "調査中", "保留", "回答済", "解決済み", "未解決"]}
  validates :replay_deadline, presence: true, inclusion: {in: ["至急", "1週間以内", "手が空いたら"]}
  validates :qa_category_id, presence: true

  # Relations
  belongs_to :user
  belongs_to :qa_category
  has_many :answers, dependent: :destroy

  # Scopes
  scope :rel_user, lambda {|user| joins(:qa_category).joins("LEFT OUTER JOIN answers ON questions.id = answers.question_id").where("qa_categories.id IN (:m) OR questions.user_id = :i OR answers.user_id = :i", {m: user.qa_categories.pluck(:id), i: user.id}).uniq.order("questions.updated_at DESC")}

  class << self
    def new_question(params, category, user)
      self.new(params).tap do |question|
        question.user = user
        question.qa_category = category
      end
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_qa_category, only: [:index, :new, :create]
  before_action :set_question, only: [:show, :edit, :update, :destroy, :answer, :unanswered]
  before_action :require_owner_or_manager_or_super, only: [:edit, :update, :destroy]

  # GET /qa_categories/1/questions/new
  def new
    @question = Question.new(replay_deadline: "手が空いたら", status: "新規")
  end

  # GET /questions/1
  def show
    @answers = @question.answers.order("created_at DESC")
  end

  # POST /qa_categories/1/questions
  def create
    @question = Question.new_question(question_params, @qa_category, current_user)

    if @question.save
      NoticeMailer.new_question(@question).deliver
      redirect_to qa_category_questions_path(@qa_category), notice: "質問を投稿しました"
    else
      render action: :new
    end
  end

  # PATCH /questions/1
  def update
    if @question.update(question_params)
      NoticeMailer.update_question(@question, current_user).deliver
      redirect_to question_path(@question), notice: "質問を変更しました"
    else
      render action: :edit
    end
  end

  # DELETE /questions/1
  def destroy
    category = @question.qa_category
    @question.destroy
    NoticeMailer.delete_question(@question, current_user).deliver
    redirect_to qa_category_questions_path(category), notice: "質問を削除しました"
  end

  # POST /questions/1/answers
  def answer
    @answer = Answer.new(message: params[:message], user_id: current_user.id, question_id: @question.id)

    if @answer.save
      redirect_to question_path(@question), notice: "コメントを投稿しました"
    else
      @message = params[:message]
      @answers = @question.answers.order("created_at DESC")
      render action: :show
    end
  end

  # DELETE /questions/1/answers/1
  def unanswered
    @answer = Answer.find(params[:answer_id])

    if current_user.id == @answer.user.id || current_user.super_user?
      @answer.destroy
      redirect_to question_path(@question), notice: "コメントを削除しました"
    else
      render file: "public/404", status: 404, layout: false
    end
  end

  private
  def question_params
    params.require(:question).permit(:title, :body, :status, :replay_deadline)
  end

  def set_question
    @question = Question.find(params[:id])
  end

  def set_qa_category
    @qa_category = QaCategory.find(params[:qa_category_id])
  end

  def require_owner_or_manager_or_super
    unless current_user.id == @question.user.id || @question.qa_category.category_manager?(current_user) || current_user.super_user?
      render file: "public/404", status: 404, layout: false and return
    end
  end
end

app/views/questions/_form.html.erb
<%= form_for([@qa_category, @question]) do |f| %>
  <%= render partial: "shared/errors", object: @question.errors %>

  <div class="row">
    <div class="col-md-3">
      <div class="form-group">
        <%= f.label :replay_deadline, "", class: "control-label" %>
        <%= f.select :replay_deadline, [["至急", "至急"], ["1週間以内", "1週間以内"], ["手が空いたら", "手が空いたら"]], {}, class: "form-control" %>
      </div>
    </div>

    <div class="col-md-3">
      <div class="form-group">
        <%= f.label :status, "", class: "control-label" %>
        <%= f.select :status, [["新規", "新規"], ["調査中", "調査中"], ["保留", "保留"], ["回答済", "回答済"], ["解決済み", "解決済み"], ["未解決", "未解決"]], {}, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :title, "", class: "control-label sr-only" %>
    <%= f.text_field :title, class: "form-control", placeholder: "タイトル", maxlength: 40, required: true %>
  </div>

  <div class="form-group">
    <%= f.label :body, "", class: "control-label sr-only" %>
    <%= f.text_area :body, class: "form-control resize", placeholder: "本文", required: true %>
  </div>

  <%= f.submit "保存", class: "btn btn-primary confirm" %>
<% end %>

app/views/questions/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <ol class="breadcrumb">
        <li><%= link_to "ホーム", home_path %></li>
        <li><%= link_to "Q&A", qa_categories_path %></li>
        <li><%= link_to @question.qa_category.name, qa_category_questions_path(@question.qa_category) %></li>
        <li><%= link_to abbreviation(@question.title), question_path(@question) %></li>
        <li class="active">質問編集</li>
      </ol>
      
      <div class="well">
        <legend>質問編集</legend>

        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/questions/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <ol class="breadcrumb">
        <li><%= link_to "ホーム", home_path %></li>
        <li><%= link_to "Q&A", qa_categories_path %></li>
        <li class="active"><%= @qa_category.name %></li>
      </ol>

      <%= render partial: "shared/notice" %>

      <legend><%= @qa_category.name %></legend>

      <p><%= link_to "質問を投稿", new_qa_category_question_path(@qa_category), class: "btn btn-inverse" %></p>

      <% if @qa_category.questions.count > 0 %>
      <table id="boards" class="table table-striped table-hover table-condensed table-condensed">
        <thead>
          <tr>
            <th>タイトル</th>
            <th>投稿日時</th>
            <th>投稿者</th>
          </tr>
        </thead>
        <tbody>
          <% @qa_category.questions.each do |question| %>
          <tr>
            <td><%= link_to question.title, question_path(question) %></td>
            <td><%= time_format question.created_at %></td>
            <td><%= link_to question.user.fullname, user_path(question.user) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <% else %>
      <p>質問が投稿されていません</p>
      <% end %>
      
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <ol class="breadcrumb">
        <li><%= link_to "ホーム", home_path %></li>
        <li><%= link_to "Q&A", qa_categories_path %></li>
        <li><%= link_to @qa_category.name, qa_category_questions_path(@qa_category) %></li>
        <li class="active">質問投稿</li>
      </ol>
      
      <div class="well">
        <legend>質問投稿</legend>

        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/questions/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <ol class="breadcrumb">
        <li><%= link_to "ホーム", home_path %></li>
        <li><%= link_to "Q&A", qa_categories_path %></li>
        <li><%= link_to @question.qa_category.name, qa_category_questions_path(@question.qa_category) %></li>
        <li class="active"><%= abbreviation @question.title %></li>
      </ol>

      <%= render partial: "shared/notice" %>
      <%= render partial: "shared/errors", object: @question.errors if @question %>

      <div class="well">
        <legend><%= @question.title %></legend>

        <div class="mb20"><%= markdown @question.body %></div>

        <span class="label label-info">投稿者</span> <%= link_to @question.user.fullname, user_path(@question.user) %>
        <span class="label label-info">期限</span> <%= @question.replay_deadline %>
        <span class="label label-info">ステータス</span> <%= @question.status %>
        <span class="label label-info">登録</span> <%= time_format @question.created_at %>
        <span class="label label-info">更新</span> <%= time_format @question.updated_at %>

        <% if current_user.id == @question.user_id || @question.qa_category.category_manager?(current_user) || current_user.super_user? %>
        <div class="mt10">
          <%= link_to "編集", edit_question_path(@question), class: "btn btn-warning btn-sm" %>
          <%= link_to "削除", question_path(@question), method: :delete, class: "btn btn-danger btn-sm", data: {confirm: "削除しますか?"} %>
        </div>
        <% end %>
      </div>

      <% @answers.each do |answer| %>
      <div class="well">
        <div class="mb20"><%= markdown answer.message %></div>

        <span class="label label-info">投稿者</span> <%= link_to answer.user.fullname, user_path(answer.user) %>
        <span class="label label-info">日時</span> <%= time_format answer.created_at %>

        <% if current_user.id == answer.user.id || current_user.super_user? %>
        <div class="mt10">
          <%= link_to "削除", unanswered_question_path(@question, answer), method: :delete, class: "btn btn-danger btn-sm", data: {confirm: "削除しますか?"} %>
        </div>
        <% end %>
      </div>
      <% end %>

      <%= form_tag answer_question_path(@question) do %>
        <div class="form-group">
          <%= label_tag :message, "", class: "control-label sr-only" %>
          <%= text_area_tag :message, @message, class: "form-control resize", placeholder: "本文", required: true %>
        </div>

        <%= submit_tag "コメント", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>