config/routes.rb
Knowledge::Application.routes.draw do
  resources :users do
    collection do
      get :search, to: :search, as: :search
    end
  end

  resources :groups do
    member do
      post :add_user, to: :add_user, as: :add_user
      delete :del_user, to: :del_user, as: :del_user
    end
  end

  resources :file_categories, except: [:show], shallow: true do
    resources :files, except: [:new, :edit, :update]
  end

  resources :board_categories, except: [:show], shallow: true do
    resources :boards do
      member do
        post :comments, to: :comment, as: :comment
        delete "comments/:comment_id", to: :uncomment, as: :uncomment
      end
    end
  end

  resources :qa_categories, shallow: true do
    member do
      post :add_user, to: :add_user, as: :add_user
      delete :del_user, to: :del_user, as: :del_user
    end

    resources :questions do
      member do
        post :answers, to: :answer, as: :answer
        delete "answers/:answer_id", to: :unanswered, as: :unanswered
      end
    end
  end
  
  controller :users do
    get :home, to: :home, as: :home
    get :profile, to: :profile, as: :profile
    patch :profile, to: :update_profile, as: :update_profile
    patch :password, to: :update_password, as: :update_password
  end

  controller :sessions do
    get :signin, to: :new, as: :signin
    post :signin, to: :create, as: :session_create
    get :signout, to: :destroy, as: :signout
  end

  controller :root do
    root to: :index
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Passwd::ActiveRecord
  define_column id: :email, salt: :salt, password: :password

  # Validations
  validates :first_name, presence: true, length: {maximum: 20}
  validates :last_name, presence: true, length: {maximum: 20}
  validates :first_name_kana, presence: true, length: {maximum: 40}
  validates :last_name_kana, presence: true, length: {maximum: 40}
  validates :email, presence: true, length: {maximum: 100}, uniqueness: true
  validates :role, inclusion: {in: 0..1}

  # Relations
  has_many :affiliations, dependent: :destroy
  has_many :groups, through: :affiliations
  has_many :attachments, dependent: :nullify
  has_many :boards, dependent: :nullify
  has_many :comments, dependent: :nullify
  has_many :answer_users, dependent: :destroy
  has_many :qa_categories, through: :answer_users
  has_many :questions, dependent: :nullify
  has_many :answers, dependent: :nullify

  # Scopes
  scope :search, lambda {|key| where("first_name LIKE :key OR first_name_kana LIKE :key OR last_name LIKE :key OR last_name_kana LIKE :key OR email LIKE :key", {key: "%#{key}%"})}

  def super_user?
    role == 1
  end

  def fullname
    "#{last_name} #{first_name}"
  end

  def fullname_kana
    "#{last_name_kana} #{first_name_kana}"
  end

  class << self
    def new_user(params)
      user = self.new(params)
      password = user.set_password
      [user, password]
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_super_user, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.order("updated_at DESC")
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1
  def show
    set_rel_knowledge
  end

  # POST /users
  def create
    begin
      ActiveRecord::Base.transaction do
        @user, password = User.new_user(user_params)
        @user.save!
        NoticeMailer.register(@user, password).deliver
      end

      redirect_to users_path, notice: "ユーザを追加しました"
    rescue
      render action: :new
    end
  end

  # PATCH /users/1
  def update
    if @user.update(user_params)
      redirect_to users_path, notice: "ユーザ情報を変更しました"
    else
      render action: :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_path, notice: "ユーザを削除しました"
  end

  # GET /users/search
  def search
    @keyword = params[:keyword]
    @users = User.search(@keyword)

    respond_to do |format|
      format.html {render action: :index}
      format.json {render action: :search}
    end
  end

  # GET /home
  def home
    @user = current_user
    set_rel_knowledge
    render :show
  end

  # PATCH /profile
  def update_profile
    if current_user.update(user_names)
      redirect_to profile_path, notice: "ユーザ名を変更しました"
    else
      render action: :profile
    end
  end

  # PATCH /password
  def update_password
    begin
      Passwd.confirm_check(params[:new_password], params[:new_password_confirmation])
      current_user.update_password(params[:old_password], params[:new_password], true)
      current_user.save!
      session[:user] = nil
      redirect_to signin_path, notice: "新しいパスワードにて再度ログインして下さい" and return
    rescue Passwd::PasswordNotMatch
      flash.now[:alert] = "パスワードが一致しません"
    rescue Passwd::AuthError
      flash.now[:alert] = "パスワードが間違っています"
    rescue Passwd::PolicyNotMatch
      flash.now[:alert] = "パスワードの強度が不足しています"
    rescue
      flash.now[:alert] = "パスワードの更新が失敗しました"
    end
    
    render action: :profile
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :email, :role)
  end

  def user_names
    params.require(:user).permit(:first_name, :last_name, :first_name_kana, :last_name_kana)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def set_rel_knowledge
    @questions = Question.rel_user(@user)
    @topics = Board.rel_user(@user)
  end
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= render partial: "shared/errors", object: @user.errors %>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :last_name, "", class: "control-label sr-only" %>
        <%= f.text_field :last_name, class: "form-control", placeholder: "苗字", maxlength: 20, required: true %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :first_name, "", class: "control-label sr-only" %>
        <%= f.text_field :first_name, class: "form-control", placeholder: "名前", maxlength: 20, required: true %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :last_name_kana, "", class: "control-label sr-only" %>
        <%= f.text_field :last_name_kana, class: "form-control", placeholder: "苗字(カナ)", maxlength: 40, required: true %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :first_name_kana, "", class: "control-label sr-only" %>
        <%= f.text_field :first_name_kana, class: "form-control", placeholder: "名前(カナ)", maxlength: 40, required: true %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :email, "", class: "control-label sr-only" %>
    <%= f.email_field :email, class: "form-control", placeholder: "メールアドレス", required: true %>
  </div>

  <div class="row">
    <div class="col-md-3">
      <div class="form-group">
        <%= f.label :role, "", class: "control-label sr-only" %>
        <%= f.select :role, {"一般" => 0, "管理者" => 1}, {}, class: "form-control" %>
      </div>
    </div>
  </div>

  <%= f.submit "保存", class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <ol class="breadcrumb">
        <li><%= link_to "ホーム", home_path %></li>
        <li><%= link_to "ユーザ一覧", users_path %></li>
        <li class="active">ユーザ編集</li>
      </ol>
      
      <div class="well">
        <legend>ユーザ編集</legend>

        <%= render "form" %>

        <div class="mt10">
          <%= link_to "削除", user_path(@user), method: :delete, class: "btn btn-danger", data: {confirm: "削除しますか?"} %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <ol class="breadcrumb">
        <li><%= link_to "ホーム", home_path %></li>
        <li class="active">ユーザ一覧</li>
      </ol>

      <legend>ユーザ一覧</legend>

      <div class="row mb20">
        <div class="col-md-10">
          <%= form_tag search_users_path, method: :get do %>
            <div class="input-group">
              <%= search_field_tag "keyword", @keyword, class: "form-control", placeholder: "Search" %>
              <span class="input-group-btn">
                <button class="btn btn-inverse" type="submit"><span class="glyphicon glyphicon-search"></span></button>
              </span>
            </div>
          <% end %>
        </div>

        <div class="col-md-2" align="right">
          <% if current_user.super_user? %>
          <%= link_to "ユーザ追加", new_user_path, class: "btn btn-inverse" %>
          <% end %>
        </div>
      </div>

      <% if @users.count > 0 %>

      <%= render partial: "shared/notice" %>
      
      <table id="users" class="table table-striped table-hover table-condensed table-condensed">
        <thead>
          <tr>
            <th>名前</th>
            <th>メールアドレス</th>
            <% if current_user.super_user? %>
            <th>権限</th>
            <th></th>
            <% end %>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td><%= link_to "#{user.fullname} (#{user.fullname_kana})", user_path(user) %></td>
            <td><%= user.email %></td>
            <% if current_user.super_user? %>
            <td><%= view_role user %></td>
            <td align="right">
              <%= link_to edit_user_path(user), class: "btn btn-warning btn-xs" do %>
              <span class="glyphicon glyphicon-pencil"></span> 編集
              <% end %>
            </td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
      <% else %>
      <p>ユーザが見つかりません</p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <ol class="breadcrumb">
        <li><%= link_to "ホーム", home_path %></li>
        <li><%= link_to "ユーザ一覧", users_path %></li>
        <li class="active">ユーザ登録</li>
      </ol>
      
      <div class="well">
        <legend>ユーザ登録</legend>

        <p class="text-info">ユーザ登録が完了すると入力したメールアドレス宛てにパスワードを送信します。</p>

        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/users/profile.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <ol class="breadcrumb">
        <li><%= link_to "ホーム", home_path %></li>
        <li class="active">ユーザ情報</li>
      </ol>

      <%= render partial: "shared/notice" %>
      <%= render partial: "shared/alert" %>

      <div class="well">
        <legend>パスワード変更</legend>

        <p>パスワードは6文字以上で半角小文字アルファベットと半角数字を含めて下さい。<br>
        パスワード変更をすると自動的にログアウトされます。新しいパスワードで再度ログインして下さい。</p>

        <%= form_tag update_password_path, method: :patch do %>

        <div class="form-group">
          <label for="old_password" class="sr-only control-label">現在のパスワード</label>
          <%= password_field_tag :old_password, nil, placeholder: "現在のパスワード", class: "form-control", required: true %>
        </div>

        <div class="form-group">
          <label for="new_password" class="sr-only control-label">新しいパスワード</label>
          <%= password_field_tag :new_password, nil, placeholder: "新しいパスワード", class: "form-control", required: true %>
        </div>

        <div class="form-group">
          <label for="new_password_confirmation" class="sr-only control-label">新しいパスワード</label>
          <%= password_field_tag :new_password_confirmation, nil, placeholder: "新しいパスワードを再入力して下さい", class: "form-control", required: true %>
        </div>

        <%= submit_tag "パスワードを変更", class: "btn btn-primary" %>

        <% end %>
      </div>

      <div class="well">
        <legend>ユーザ情報変更</legend>

        <%= form_for current_user, url: update_profile_path, method: :patch do |f| %>

        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <%= f.label :last_name, "", class: "control-label sr-only" %>
              <%= f.text_field :last_name, class: "form-control", placeholder: "苗字", maxlength: 20 %>
            </div>
          </div>

          <div class="col-md-6">
            <div class="form-group">
              <%= f.label :first_name, "", class: "control-label sr-only" %>
              <%= f.text_field :first_name, class: "form-control", placeholder: "名前", maxlength: 20 %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <%= f.label :last_name_kana, "", class: "control-label sr-only" %>
              <%= f.text_field :last_name_kana, class: "form-control", placeholder: "苗字(カナ)", maxlength: 40 %>
            </div>
          </div>

          <div class="col-md-6">
            <div class="form-group">
              <%= f.label :first_name_kana, "", class: "control-label sr-only" %>
              <%= f.text_field :first_name_kana, class: "form-control", placeholder: "名前(カナ)", maxlength: 40 %>
            </div>
          </div>
        </div>

        <%= submit_tag "ユーザ情報を変更", class: "btn btn-primary" %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3" style="font-size:small;">
      <h6><%= @user.fullname %></h6>
      <p><%= @user.fullname_kana %></p>
      <span class="glyphicon glyphicon-envelope"></span> <%= @user.email %>

      <hr>

      <h6>グループ</h6>
      <% if @user.groups.count > 0 %>
      <% @user.groups.each do |group| %>
      <%= link_to group.name, group_path(group) %><br>
      <% end %>
      <% else %>
      所属しているグループはありません。
      <% end %>

      <% if @user.qa_categories.count > 0 %>
      <hr>

      <h6>Q&Aカテゴリ</h6>

      <% @user.qa_categories.each do |category| %>
      <%= link_to category.name, qa_category_path(category) %><br>
      <% end %>
      <% end %>
    </div>

    <div class="col-md-9">
      <div class="row">
        <div class="col-md-12">
          <div class="well">
            <h6>関連するトピック</h6>
            <hr>

            <% if @topics.count > 0 %>
            <table class="table table-striped table-hover table-condensed table-condensed">
              <thead>
                <tr>
                  <th>タイトル</th>
                  <th>投稿者</th>
                </tr>
              </thead>

              <tbody>
                <% @topics.each do |topic| %>
                <tr>
                  <td><%= link_to topic.title, board_path(topic) %></td>
                  <td><%= link_to topic.user.fullname, user_path(topic.user) %></td>
                </tr>
                <% end %>
              </tbody>
            </table>
            <% else %>
            <p>関連するトピックはありません</p>
            <% end %>
          </div>

          <div class="well">
            <h6>関連するQ&A</h6>
            <hr>
            
            <% if @questions.count > 0 %>
            <table class="table table-striped table-hover table-condensed table-condensed">
              <thead>
                <tr>
                  <th>タイトル</th>
                  <th>投稿者</th>
                </tr>
              </thead>

              <tbody>
                <% @questions.each do |question| %>
                <tr>
                  <td><%= link_to question.title, question_path(question) %></td>
                  <td><%= link_to question.user.fullname, user_path(question.user) %></td>
                </tr>
                <% end %>
              </tbody>
            </table>
            <% else %>
            <p>関連するQ&Aはありません</p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>