config/routes.rb
Knowledge::Application.routes.draw do
  resources :users do
    collection do
      get :search, to: :search, as: :search
    end
  end

  resources :groups do
    member do
      post :add_user, to: :add_user, as: :add_user
      delete :del_user, to: :del_user, as: :del_user
    end
  end

  resources :file_categories, except: [:show], shallow: true do
    resources :files, except: [:new, :edit, :update]
  end

  resources :board_categories, except: [:show], shallow: true do
    resources :boards do
      member do
        post :comments, to: :comment, as: :comment
        delete "comments/:comment_id", to: :uncomment, as: :uncomment
      end
    end
  end

  resources :qa_categories, shallow: true do
    member do
      post :add_user, to: :add_user, as: :add_user
      delete :del_user, to: :del_user, as: :del_user
    end

    resources :questions do
      member do
        post :answers, to: :answer, as: :answer
        delete "answers/:answer_id", to: :unanswered, as: :unanswered
      end
    end
  end
  
  controller :users do
    get :home, to: :home, as: :home
    get :profile, to: :profile, as: :profile
    patch :profile, to: :update_profile, as: :update_profile
    patch :password, to: :update_password, as: :update_password
  end

  controller :sessions do
    get :signin, to: :new, as: :signin
    post :signin, to: :create, as: :session_create
    get :signout, to: :destroy, as: :signout
  end

  controller :root do
    root to: :index
  end
end

app/views/shared/_alert.html.erb
<% if flash[:alert] %>
<div class="alert alert-danger">
  <button class="close" data-dismiss="alert">&times;</button>
  <%= flash[:alert] %>
</div>
<% end %>

app/views/shared/_errors.html.erb
<% if errors.any? %>
<% errors.full_messages.each do |msg| %>
<div class="alert alert-danger">
  <button class="close" data-dismiss="alert">&times;</button>
  <%= msg %>
</div>
<% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="container">
  <div class="row">
    <div class="col-md-12">
      <span id="copyright">Copyright &copy; 2013 <a href="http://i2bskn.com">i2bskn</a></span>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="container">
  <nav class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".target">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Knowledge", home_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse target">
      <ul class="nav navbar-nav">
        <li><%= link_to "ホーム", home_path %></li>
        <li><%= link_to "ユーザ", users_path %></li>
        <li><%= link_to "グループ", groups_path %></li>
        <li><%= link_to "ファイル", file_categories_path %></li>
        <li><%= link_to "トピック", board_categories_path %></li>
        <li><%= link_to "Q&A", qa_categories_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <span class="glyphicon glyphicon-cog"></span> <%= current_user.fullname %><b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to profile_path do %>
              <span class="glyphicon glyphicon-user"></span> ユーザ情報
              <% end %>
            </li>
            <li>
              <%= link_to signout_path do %>
              <span class="glyphicon glyphicon-off"></span> ログアウト
              <% end %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_notice.html.erb
<% if flash[:notice] %>
<div class="alert alert-info">
  <button class="close" data-dismiss="alert">&times;</button>
  <%= flash[:notice] %>
</div>
<% end %>